# Generated by Django 3.0.8 on 2020-07-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200719_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
